# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("BlockSite.authenticate", false);
user_pref("BlockSite.enabled", true);
user_pref("BlockSite.listtype", "blacklistRadio");
user_pref("BlockSite.locations.0", "http://filapp1.imgsmail.ru/");
user_pref("BlockSite.locations.1", "");
user_pref("BlockSite.regexp.0", "^http\\:\\/\\/filapp1\\.imgsmail\\.ru\\/");
user_pref("BlockSite.regexp.1", "");
user_pref("BlockSite.removeLinks", true);
user_pref("BlockSite.showWarning", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1361092739);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1361089475);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1361092579);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.migration.version", 8);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionhistory.max_entries", 2);
user_pref("browser.sessionhistory.max_total_viewers", 0);
user_pref("browser.sessionstore.interval", 150000);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.startup.homepage_override.buildID", "20130201185534");
user_pref("browser.startup.homepage_override.mstone", "18.0.2");
user_pref("browser.syncPromoViewsLeft", 3);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"{6d43fee4-72e7-4290-b75a-b898e4f4676d}\":{\"version\":\"1.1\",\"type\":\"extension\",\"descriptor\":\"/home/%USER%/.mozilla/firefox/06teufoy.TESTING/extensions/{6d43fee4-72e7-4290-b75a-b898e4f4676d}\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "langpack-ru%40firefox.mozilla.org:18.0.2,langpack-en-ZA%40firefox.mozilla.org:18.0.2,langpack-en-GB%40firefox.mozilla.org:18.0.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:18.0.2");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1359282105000},\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1359282106000},\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1359282105000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1361000717000},\"langpack-ru@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-ru@firefox.mozilla.org.xpi\",\"mtime\":1359758444000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1359758437000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1359758437000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1361000715000}}},{\"name\":\"app-profile\",\"addons\":{\"{6d43fee4-72e7-4290-b75a-b898e4f4676d}\":{\"descriptor\":\"/home/%USER%/.mozilla/firefox/06teufoy.TESTING/extensions/{6d43fee4-72e7-4290-b75a-b898e4f4676d}\",\"mtime\":1361089517000}}}]");
user_pref("extensions.lastAppVersion", "18.0.2");
user_pref("extensions.lastPlatformVersion", "18.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/locale");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20130201185534");
user_pref("gecko.mstone", "18.0.2");
user_pref("general.smoothScroll", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("layout.spellcheckDefault", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.prefetch-next", false);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("toolkit.startup.last_success", 1361092848);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1363681478);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
